// Accept incomplete drafts but reject malformed structures before rendering/importing.
const record = (v: unknown): v is Record<string, unknown> => !!v && typeof v === "object" && !Array.isArray(v);
const strings = (v: unknown) => Array.isArray(v) && v.every(x => typeof x === "string");
const localized = (v: unknown) => record(v) && typeof v.en === "string" && typeof v.el === "string";
const fields = (v: Record<string, unknown>, names: string[]) => names.every(name => typeof v[name] === "string");
export function isDraftWorkspace(value: unknown): boolean {
  if (!record(value) || value.version !== 1 || !Array.isArray(value.studios) || !Array.isArray(value.news) || (value.trash !== undefined && !strings(value.trash))) return false;
  const piece = (p: unknown) => record(p) && fields(p,["id","imageUrl","caption"]) && (p.kind === undefined || p.kind === "tattoo" || p.kind === "piercing") && (p.styleId === undefined || typeof p.styleId === "string") && (p.priceEUR === undefined || typeof p.priceEUR === "number");
  const artist = (a: unknown) => record(a) && fields(a,["id","slug","name","studioSlug","avatarUrl","instagramHandle"]) && localized(a.role) && localized(a.bio) && typeof a.yearsExperience === "number" && strings(a.styleIds) && Array.isArray(a.portfolio) && a.portfolio.every(piece) && (a.discipline === undefined || ["tattoo","piercing","both"].includes(String(a.discipline))) && (a.piercingSpecialities === undefined || typeof a.piercingSpecialities === "string");
  return value.studios.every(s => record(s) && fields(s,["id","slug","name","cityId","address","heroImageUrl","priceBand","instagramHandle","phone"]) && localized(s.neighborhood) && localized(s.description) && localized(s.hours) && strings(s.galleryImages) && strings(s.styleIds) && typeof s.rating === "number" && typeof s.reviewCount === "number" && typeof s.avgSessionEUR === "number" && typeof s.promoted === "boolean" && Array.isArray(s.artists) && s.artists.every(artist) && (s.websiteUrl === undefined || typeof s.websiteUrl === "string")) && value.news.every(n => record(n) && fields(n,["id","slug","imageUrl","sourceName","publishedAt"]) && localized(n.title) && localized(n.excerpt) && strings(n.tags) && (n.sourceUrl === undefined || typeof n.sourceUrl === "string"));
}
